# Home redirection to the admin
home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: admin_city_index
        permanent: true

# Lexik JWT login handler
api_login_check:
    path: /api/login_check

# Logout routing
admin_logout:
   path: /admin/logout